### ISSUE TITLE
Not allowed to update primer once sequences are processed, but primer column is ignored in Illumina processing workflow,  

### ISSUE THREAD

**Issue by jessicalmetcalf** [biocore/qiita#1510]
This is just a note that you may want to consider allowing the primer column to be updated in prep templates with processed data in cases in which the primers are not used in the workflow.  This just prevents unnecessary preprocessing. Thanks team!

**Comment by josenavas** [comment]
This has been fixed in the dev branch

**Comment by antgonza** [comment]
Still an issue, just tried to modify one and got the following error:
<img width="1643" alt="screen shot 2017-12-30 at 5 25 52 am" src="https://user-images.githubusercontent.com/2014559/34454143-fd4e4a9e-ed21-11e7-8cab-4b1869ac0123.png">

**Comment by ackermag** [comment]
This is a specific problem when studies are checked for submission to EBI - if primer is wrong you have to reprocess the study.  Also, if you try to change primer and other columns the resulting error makes it look like it is not possible to change any of the columns.
<img width="1323" alt="message" src="https://user-images.githubusercontent.com/2014592/44160512-7d5f1f00-a06f-11e8-853c-582338cadbe3.png">
