### ISSUE TITLE
edit artifact name

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2173]
It would be nice to have the current name pre-filled in the textbox, when updating the name in cases it is not the default name and one just wants to e.g. fix a typo

**Comment by antgonza** [comment]
@tkosciol, I think this has been solved in the release candidate, right?

**Comment by adswafford** [comment]
This is still an issue since the goal is to have the name appear in the popup box.

For example, if I have renamed my object 'test1a_stefan_gaveThisAReallyLongNameAndHeJustWants_to_add_the_number_to_the_end' and I want to rename it 'test1a_stefan_gaveThisAReallyLongNameAndHeJustWants_to_add_the_number_to_the_end_1', I can't without some roundabout copy-pasting, so instead of the pop-up text box being empty he wants to have it say 'test1a_stefan_gaveThisAReallyLongNameAndHeJustWants_to_add_the_number_to_the_end'.

Did I interpret that correctly @sjanssen2 ?

**Comment by josenavas** [comment]
Fixed in dev
