### ISSUE TITLE
Download link for admins in file upload section not working

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2508]
Study 11640; I tried to download the user's uploaded .fna to help troubleshoot but the link was non functional:

https://qiita.ucsd.edu/download_upload/11640/merged.MR.prtrim.upf.filt.derep.mc2.repset.fna
![image](https://user-images.githubusercontent.com/27017606/36440678-08d10650-1625-11e8-93db-360c1686ad17.png)

**Comment by antgonza** [comment]
This is a configuration error that has been corrected and we are working on avoiding in the future. Anyway, it's working now so closing.

**Comment by adswafford** [comment]
Reopening, as this is still not working for me: https://qiita.ucsd.edu/download_upload/11640/merged.MR.prtrim.upf.filt.derep.mc2.repset.fna
https://qiita.ucsd.edu/download_upload/11129/METABOLOMICS-SNETS-30061367-download_biom-main.biom

**Comment by antgonza** [comment]
The links should be working now. @adswafford, could you close if it works for you? Thanks!

**Comment by antgonza** [comment]
This has been solved. Closing, please reopen otherwise.
